- bin/react-docgen.js
Updating reference to argv.o to be the output variable we set.
Updating output to point to argv.out instead of argv.o because abbreviations aren't the representation on the argv object
> Fix for using the out argument from the console

- README.md
- Changes `do` to `to`.
- Adds closing `|` to match rows for table above.
- Condenses two short lines into one line still shorter than 80 char to match surrounding lines.
> Changes some spelling and markdown in README

- src/babylon.js
They are part of Stage 0 features: https://babeljs.io/docs/usage/experimental/#stage-0
> Enable es7.doExpressions and es7.functionBind

- package.json
To run the tests it is not needed to transpile them beforehand, and for the npm package
the mocks and tests are ignored anyway.
So I think it is safe to ignore them in the babel transformation.
The tests probably fail due to #49 .
> Do not compile tests and mocks to dist

- README.md
- flow/react-docgen.js
- flow/recast.js
- package.json
- src/handlers/__tests__/flowTypeDocBlockHandler-test.js
- src/handlers/__tests__/flowTypeHandler-test.js
- src/handlers/flowTypeDocBlockHandler.js
- src/handlers/flowTypeHandler.js
- src/handlers/index.js
- src/handlers/propDocBlockHandler.js
- src/main.js
- src/resolver/index.js
- src/utils/__tests__/getFlowType-test.js
- src/utils/__tests__/getTypeAnnotation-test.js
- src/utils/getFlowType.js
- src/utils/getFlowTypeFromReactComponent.js
- src/utils/getTypeAnnotation.js
- src/utils/isRequiredPropType.js
- src/utils/isStatelessComponent.js
- src/utils/isUnreachableFlowType.js
- src/utils/resolveToValue.js
- src/utils/setPropDescription.js
I started working on adding support for flow types.
So far I only tried to get it working for classes, and it already works nicely for this usecase, but only for string type and declared types. The code although is far away from nice yet. It also needs a patched version of ast-types, which I will create a PR also soon.
I opened this PR already so that interested people can join and already have a look and maybe give feedback.
Will fix #31
This needs to be done:
> Support for flow types

- bin/__tests__/react-docgen-test.js
- package.json
- src/handlers/__tests__/propDocblockHandler-test.js
- src/utils/__tests__/docblock-test.js
child_process.spawn isn't windows compatibile, so using cross-spawn-aync
end of line tests for docblocks fails on windows, using Node's os.EOL module to handle that in certain tests.
Test pass on windows, hopefully the changes also pass on the CI.
> Pass tests on Windows

- .gitignore
- src/utils/__tests__/getParameterName-test.js
- src/utils/getMethodDocumentation.js
- src/utils/getParameterName.js
- src/utils/index.js
- src/utils/isReactComponentMethod.js
The current implementation returns an empty string for parameter name when using rest parameters, default parameter value or destructuring. I added basic support for these cases so at least something is displayed. Not sure what to do exactly with parameters destructuring but just printing it seemed good enough for now.
It also adds a missing component lifecycle method `componentDidReceiveProps` and reorders them alphabetically.
cc @fkling @danez
> Component methods - Improve parameter name parsing and add missing react component method

- .travis.yml
- src/resolver/__tests__/findExportedComponentDefinition-test.js
This suite of tests was *always* being *erroneously* marked as passing due to the `describe.only` on line 486. Even adding `expect(false).toBeTruthy();` to any test would result in this suite still passing.
This PR also fixes the broken tests, including a syntax error in one of the source fixtures.
Note: tests on `master` are currently failing on Node 6.
> Fix findExportedComponentDefinition unit tests

- src/handlers/__tests__/flowTypeHandler-test.js
- src/handlers/flowTypeHandler.js
This allows intersection and union types to be used as
Props. Fixes #75
> Allow TypeAnnotations which group other types

- src/utils/getMethodDocumentation.js
To support some proposed React Native doc updates, here are two changes:
1. Expose the type name, ex: the code below would like to see type.name set to StatusBarStyle instead of $Enum:
export type StatusBarStyle = $Enum<{
...
}
2. Expose whether a method's parameter is optional or not. Currently this isn't brought out.
> Change typealias name add param optional

- src/utils/__tests__/parseJsDoc-test.js
- src/utils/parseJsDoc.js
Found an issue with optional parameter types when documenting a component without Flow annotations and having to rely on jsdoc format. The type is erroneously passed back as `null` as the logic looks for `type.name` and it should instead look for `type.expression.name` for optional types.
As part of this change, I also exposed an `optional` property for the parameter for doc formatting purposes.
Doctrine: with optional parameter
https://tonicdev.com/576a0e802ae39e13008feb2f/576a0e802ae39e13008feb30
Doctrine: parameter required
https://tonicdev.com/576a0e802ae39e13008feb2f/576a13d18f0383130020cf21
From logging the internals, this is what the ast looks after passing an optional parameter through doctrine and before the type info is extracted by react-docgen:
```
{
"description": "Replace a …
```
> Handle optional param types when parsing jsdoc format

- .travis.yml
- flow/react-docgen.js
- package.json
This makes travis to run flow, eslint and the tests.
I hope it is okay that I added flow. If not I can als remove it again form this PR and just fix the flow error.
```
src/utils/getMethodDocumentation.js:48
48:       type = getFlowType(typePath);
^^^^^^^^^^^^^^^^^^^^^ function call
50:         type.alias = typePath.node.id.name;
^^^^^ property `alias`. Property not found in
50:         type.alias = typePath.node.id.name;
^^^^ object type
```
> Add flow-bin, update jest and fix flow error

- .travis.yml
By setting "sudo: required" we force travis to use a bigger Ubuntu box
instead of running in a docker container.
See [travis documentation](https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments) for more information.
Relates to: #110
> Force travis to use bigger machine / non-docker

- src/utils/__tests__/resolveToModule-test.js
- src/utils/__tests__/resolveToValue-test.js
- src/utils/resolveToValue.js
Previously react-docgen did not resolve namespaced imports correctly to
their importing modules.
Example:
```javascript
import * as React from 'react';
export default function Button({ text }) {
return (<button>{text}</button>);
}
Button.propTypes = {
text: React.PropTypes.string.isRequired,
};
```
The prop `text` would always show up as "custom" with a raw value of
"React.PropTypes.string.isRequired" instead of correctly detecting
`React.PropTypes.string` to be a part of the imported `React`
namespace and correctly detecting the propType as a required string.
This commit adds support for `ImportNamespaceSpecifier` to the
`resolveToValue` and `resolveToModule` utility functions.
> Allow namespaced imports to be resolved correctly

- src/resolver/__tests__/findAllExportedComponentDefinitions-test.js
- src/resolver/findAllExportedComponentDefinitions.js
- src/resolver/index.js
This resolver is basically a direct copy of the
"findExportedComponentDefinition" resolver including the tests.
The most significant difference is, that this resolver does not throw
when it encounters more than one component definition.
It adds all found component definitions into an array (deduplicated)
and returns that array at the end of execution.
> Add resolver "findAllExportedComponentDefinitions"

- src/utils/__tests__/getMemberExpressionValuePath-test.js
- src/utils/getMemberExpressionValuePath.js
When searching for a MemberExpresion (i.e. "propTypes") that is defined
on an object (ArrowFunctionExpression, FunctionExpression,
FunctionDeclaration or VariableDeclaration), take the local Identifier
into account to find the member of the correct object.
Before:
When using multiple components per file, it would for every component
take the propTypes of the last component encountered.
```javascript
function Component1() { return (<i />); }
Component1.propTypes = { a: React.PropTypes.string };
function Component2() { return (<b />); }
Component2.propTypes = { b: React.PropTypes.number };
```
After:
Now it checks whether the property of the MemberExpression actually
belongs to the correct object.
> Verify that the MemberExpression that is being searched for belongs to the correct object

- .eslintrc
- flow/react-docgen.js
- src/handlers/__tests__/flowTypeDocBlockHandler-test.js
- src/handlers/__tests__/flowTypeHandler-test.js
- src/handlers/componentMethodsHandler.js
- src/handlers/flowTypeDocBlockHandler.js
- src/handlers/flowTypeHandler.js
- src/utils/__tests__/getMethodDocumentation-test.js
- src/utils/__tests__/getTypeAnnotation-test.js
- src/utils/getFlowTypeFromReactComponent.js
- src/utils/getMethodDocumentation.js
This is basically #97 but without throwing an error.
I also enabled to eslint rules to detect undefined and unused variables.
Closes #97
> Fix intersection and union flow types

- src/handlers/__tests__/defaultPropsHandler-test.js
- src/handlers/defaultPropsHandler.js
A common pattern in libraries is to set a default prop value as an imported component, for eg. a transition component for a dialog.
#63 has an example + a workaround (not the most elegant however, involves using a functional component to return the default component).
Right now, `react-docgen` throws an error on components implementing this pattern as `ImportDefaultDeclaration` is not a printable type.
This PR adds a conditional after the `resolveToValue(path)` call in `getDefaultValue(path)` to check if the node is an import declaration. If so, it returns the `.name` property of the original node (so the function/component name).
> Check for import declaration type when getting default values, resolves #63

- README.md
- bin/react-docgen.js
hi,
i added a cli parameter 'exclude' to confugure some filename patterns from parsing.
the default is set to ['**index.js**'] because is a common use to organize components in indexed namespaces
Es.
```
/package.json
/app.js
/components/
/components/namespace1/index.js
/components/namespace1/Component1.js
/components/namespace1/Component2.js
```
where index.js is:
```
export Component1 from './Component1'
export Component2 from './Component2'
```
and app.js imports these components with:
`import {Component1, Component2} from './components/namespace1'`
i know that someone use the pattern `/components/ComponentName/index.js` (i don't like this) so... maybe is better to set [] as default...
> added exclude cli parameter to exclude files by pattern

- src/resolver/__tests__/findAllExportedComponentDefinitions-test.js
- src/resolver/__tests__/findExportedComponentDefinition-test.js
- src/resolver/findAllExportedComponentDefinitions.js
- src/resolver/findExportedComponentDefinition.js
- src/utils/__tests__/resolveHOC-test.js
- src/utils/resolveHOC.js
Fixes https://github.com/reactjs/react-docgen/issues/80
> Added support for resolving exported components within HOCs

- src/utils/__tests__/getPropType-test.js
- src/utils/getPropType.js
React has introduced a new primitive PropType "symbol".
https://github.com/facebook/react/pull/6377
This change adds support for that propType so that it is not reported
as "custom".
> Add support for newly introduced PropTypes "symbol"

- bin/__tests__/react-docgen-test.js
- package.json
- src/__tests__/__snapshots__/main-test.js.snap
- src/__tests__/fixtures/component_1.js
- src/__tests__/main-test.js
- src/handlers/__tests__/componentMethodsJsDocHandler-test.js
- src/handlers/__tests__/propTypeHandler-test.js
- src/resolver/__tests__/findAllComponentDefinitions-test.js
- src/resolver/__tests__/findAllExportedComponentDefinitions-test.js
- src/resolver/__tests__/findExportedComponentDefinition-test.js
- src/utils/__tests__/docblock-test.js
- src/utils/__tests__/getMemberExpressionRoot-test.js
- src/utils/__tests__/getMemberValuePath-test.js
- src/utils/__tests__/normalizeClassDefinition-test.js
- src/utils/__tests__/resolveExportDeclaration-test.js
- src/utils/__tests__/resolveToValue-test.js
- src/utils/resolveToValue.js
- src/utils/traverse.js
In the following example, resolveToValue wouldn't resolve to the value
assigned to "React" because it only looks at the variable
definition, not at assignments to the variable:
```
var React;
React = require('react');
module.exports = React.createClass(...);
```
This diff fixes that. It will make a shallow traversal over the scope
where the variable is defined and look for the last assignment to the
variable.
---
I'm also trying to improve tests by storing component definitions that
are known to have been broken in `src/__tests__/fixtures/`. Adding more
components over time will strengthen the test suit and help catch
regressions.
Also updates to jest v15.
> Make resolveToValue consider assignments to identifiers (fixes #58)

- src/handlers/__tests__/defaultPropsHandler-test.js
- src/handlers/defaultPropsHandler.js
Fixes https://github.com/reactjs/react-docgen/issues/69,
With this PR we first search for `defaultProps` of the stateless component (if stateless) and then check using `defaultProps` or `getDefaultProps`, it will overwrite the `defaultProps` of the stateless component if any is found.
Let me know what you think of it, this is my first time working with AST, so I'm prepared for all feedback 😅 .
> Add checking stateless component default props

- bin/react-docgen.js
I run into an issue, that the output from `react-docgen` is cut off, if the output is too big.
This only happens if I try to pipe the output like so:
```
react-docgen ./components | node ./buildDocs.js
```
Or like so:
```
let spawn = require('child_process').spawn;
let child = spawn('react-docgen', ['./Components']);
let buffers = [];
child.stdout.on('data', data => {
buffers.push(data);
});
child.stdout.on('close', () => {
let buffer = Buffer.concat(buffers);
console.log(`${buffer}`);
});
```
After some research I found this issue:
https://github.com/visionmedia/mocha/issues/333
And it works with the solution they used:
https://github.com/mochajs/mocha/pull/1440/files
So hopefully you can use this fix. I will try to help where I can to get it merged. Another solution could be this …
> fix(bin): write into streams before exit

- src/handlers/__tests__/defaultPropsHandler-test.js
- src/handlers/defaultPropsHandler.js
Fixes issue https://github.com/reactjs/react-docgen/issues/131.
The issue was that props that didn't have any defaults were still evaluated (since the prop was indeed referenced) and received `{ value: propName, computed: 'true' }` as defaultProp. I also found an issue that imported values were not properly recognised by defaultprops for stateless components.
Both issues are fixed with this PR.
I can explain the issue more explicitly next week, I am gone this weekend.
> Fix issue with computed props for functional components

- README.md
- bin/__tests__/react-docgen-test.js
- bin/react-docgen.js
As __mocks__ is used in manual mocks on jest
cf. https://facebook.github.io/jest/docs/manual-mocks.html
> Add __mocks__ folder to default ignoreDir

- src/utils/__tests__/isStatelessComponent-test.js
- src/utils/isReactCloneElementCall.js
- src/utils/isStatelessComponent.js
Support for `cloneElement` on stateless components.
Related #107
> Support cloneElement calls

- bin/react-docgen.js
- package.json
Fixes #56 
This is a pretty straight port over to commander.
Benefits:
- Removes dependency on a dead package.
- Commander only has one dependency: graceful-readlink, making install times just a tiny tiny bit faster ;)
> Replace nomnom with commanderjs

- src/__tests__/fixtures/component_2.js
- src/utils/isStatelessComponent.js
* Fixes https://github.com/reactjs/react-docgen/issues/136
* Add `isValidCalleeType()` check for CallExpresion and ArrayExpression and Literal
* Improves on https://github.com/reactjs/react-docgen/pull/134 by validating the `calleeValue`'s object type, which happens to be mutated in-place during the `while` loop.
> Guard against infinite loop on chained or static methods

- src/__tests__/__snapshots__/main-test.js.snap
- src/__tests__/fixtures/component_4.js
- src/utils/getPropType.js
Prevent react-docgen from crashing when spread operations are passed to shape(). Behaviour is similar to how spread operations are handled in normal propType definitions.
> Ignore SpreadProperties in shapes

- src/__tests__/fixtures/component_2.js
- src/resolver/__tests__/findAllExportedComponentDefinitions-test.js
- src/resolver/__tests__/findExportedComponentDefinition-test.js
Exporting the same identifier twice is not allowed by spec
This will throw with babylon >=6 and maybe other parsers
> Fix tests: Do not export component twice

- src/utils/isReactModuleName.js
This PR adds @developit's [proptypes module](https://github.com/developit/proptypes) to the list of recognised React modules, for better support of engines other than Facebook's React. In this case, I'm using it with [Preact](https://preactjs.com/).
Having looked at #96, I don't know if adding another hardcoded value to the list of modules is the way you want to go. If you prefer a more flexible solution of being able to supply the names of the modules to validate against, I can also look into that if you give me some pointers.
Thanks!
> Add developit/proptypes to allowed module names

- .npmignore
I found a coverage folder in this module which was 1mb, so I thought I'd remove it.
:heart:
> Remove coverage folder from NPM package

- src/__tests__/__snapshots__/main-test.js.snap
- src/__tests__/fixtures/component_6.js
- src/utils/isReactModuleName.js
This resolves #171. 
[React 15.5.0](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html) introduced a new `prop-types` package and deprecated `React.PropTypes`. Currently `react-docgen` doesn't recognize the [`prop-types`](https://www.npmjs.com/package/prop-types) package as a React module, so it sets the `type` to `custom` for all PropTypes.
> Add support for new prop-types package

- src/__tests__/__snapshots__/main-test.js.snap
- src/__tests__/fixtures/component_7.js
- src/utils/__tests__/isReactCreateClassCall-test.js
- src/utils/isReactCreateClassCall.js
Fixes #176, adding support for the new create-react-class package.
I'm not familiar with recast (but have dabbled with estraverse), so any tips or suggestions are appreciated.  Thanks!
> Support for create-react-class package

- src/handlers/__tests__/flowTypeHandler-test.js
- src/utils/getFlowTypeFromReactComponent.js
> feat(react): Support new flow 0.53 annotations

- package.json
- tests/setupTestFramework.js
This improves the output of the matcher because I wasn't able to see what the diff in the AST actually was :)
This also makes use of js features that node 4+ supports.
> test(matcher): Add a readable message with diff to the AST matcher

- .npmignore
- package.json
This will now only include `bin/` and `dist/` in the package and leave out all other files (besides LICENSE and README.md)
> chore(publish): change to npm whitelist to exclude unnecessary files

- src/utils/__tests__/getPropType-test.js
- src/utils/__tests__/resolveObjectKeysToArray-test.js
- src/utils/getPropType.js
- src/utils/resolveObjectKeysToArray.js
Creates a new util to extract keys from `Object.keys()` and `ObjectExpressions` when used inside of `oneOf()`
It also follows spreads and tries to resolve them. Currently it bails out if either a `Property` is computed and the computed key is not a `Literal` or if a spread cannot be resolved.
Getters will be handled the same as normal properties, but setters will be ignored. Not sure if this makes 100% sense, but this can be easily changed.
This fixes #153.
As a follow up the same can be done easily for `Object.values`.
!! When this gets merged to v3, `SpreadProperty` needs to be replaced with `SpreadElement` !!
> feat(resolve): resolve Object.keys() in PropType.oneOf()

- src/utils/__tests__/getMemberExpressionValuePath-test.js
- src/utils/__tests__/getMemberValuePath-test.js
- src/utils/getMemberExpressionValuePath.js
- src/utils/getMemberValuePath.js
Adding the same functionality to v3 as proposed in.
https://github.com/reactjs/react-docgen/pull/195
> v3-dev Allow getMemberValuePath to get data from a TaggedTemplateExpression

- README.md
- src/utils/__tests__/getFlowType-test.js
- src/utils/getFlowType.js
Add support for flow functions with parameters that doesn't have a name.
Eg. `value: string => void` and `value: (string, number) => void`
This kind of functions ins't currently supported by `react-docgen`, and it's unable to parse the file.
Source: [flow](https://flow.org/en/docs/types/functions/#toc-function-types)
> Add support for function paramets without names

- package.json
- src/handlers/componentDocblockHandler.js
- src/utils/docblock.js
- yarn.lock
The comment attachment changed in babylon a little bit, because decorators are not considered part of the class declaration.
This fixes react-docgen to make all the usecases still work.
> Update babylon to latest beta and fix detection of comments

- src/utils/__tests__/getFlowType-test.js
- src/utils/getFlowType.js
- src/utils/getFlowTypeFromReactComponent.js
Fixes #216
Add support for :
```js
type Props = { component: typeof MyComponent };
```
And also for all the exported React Types like `React.Node, React.Element`, etc.
see tests for examples.
> Add support for typeof types and React.* types

- src/utils/__tests__/getFlowType-test.js
- src/utils/getFlowType.js
- src/utils/resolveObjectKeysToArray.js
`resolveObjectExpressionToNameArray` could be extracted into a separate handler, but I tried to keep the diff for now as minimal as possible
Fixes #154
>  Resolve flow $Keys<> to union type

- src/utils/__tests__/isStatelessComponent-test.js
- src/utils/isStatelessComponent.js
Besides refactoring the module it now supports components that return
LogicalExpressions or ConditionalExpressions. I also removed the "manual" scope check
and instead use the scope returned by `ast-types` and compare that one.
The test have been rewritten to be composed of certain parameters instead
of hardcoding all possible testcases.
```js
function MyComponent () {
return a ? <jsx /> : b 
// or
return a || <jsx />;
}
```
This should improve some cases reported in #232
A further improvement would be to also account for `.forEach`, `.reduce` etc.
> isStatelessComponent: Handle Logical and Conditional Expressions

- package.json
- src/__tests__/__snapshots__/main-test.js.snap
- src/__tests__/fixtures/component_11.js
- src/parse.js
- src/utils/postProcessDocumentation.js
Definitely a WIP, but thought I'd get a PR going to have something to discuss on. This branch adds a post-processing step for documentation objects. Currently, this post-processing step only does what's needed to "fix" #221, but I can imagine we could use it for validation of documentation objects as well? I haven't added any tests yet. Let me know what you think!
> Added post-processing step for documentation objects

- src/Documentation.js
- src/__tests__/__snapshots__/main-test.js.snap
- src/__tests__/fixtures/component_5.js
- src/__tests__/fixtures/component_6.js
- src/handlers/__tests__/propTypeHandler-test.js
- src/handlers/index.js
- src/handlers/propTypeHandler.js
- src/main.js
Hi,
this PR builds up on the PR #130 that didn't show any activity for about a year now.
It introduces two new handlers for `contextType` and `childContextType` based on existing `propTypeHandler`.
I've rebased the stale branch, updated 2 fixtures  and snapshots (as was requested in the above PR) and also fixed some linter errors. Let me know if any other changes are required, please.
Thanks,
G.
> add context handlers

- src/utils/__tests__/isReactComponentClass-test.js
- src/utils/isReactComponentClass.js
Certain react components may have multiple layers of inheritance and don't necessarily have a render function if it has a base class that handles rendering. In that case, `react-docgen` would fail to parse the file.
This PR:
> Adding `@extends React.Component` support to isReactComponentClass

- README.md
- bin/react-docgen.js
- package.json
- src/babelParser.js
- src/handlers/__tests__/componentDocblockHandler-test.js
- src/main.js
- src/parse.js
- tests/utils.js
- yarn.lock
Add option to switch back to legacy decorators parsing
This is a breaking change as it will by default only parse the latest decorators spec which changed the syntax.
>  Migrate babylon to @babel/parser

- src/handlers/__tests__/propTypeHandler-test.js
- src/utils/__tests__/getMemberExpressionRoot-test.js
- src/utils/__tests__/resolveHOC-test.js
- src/utils/__tests__/resolveObjectKeysToArray-test.js
- src/utils/__tests__/resolveToValue-test.js
- src/utils/resolveToValue.js
- tests/setupTestFramework.js
> fix: resolve value to a proper node instead of an array

- src/__tests__/__snapshots__/main-test.js.snap
- src/__tests__/fixtures/component_15.js
- src/handlers/flowTypeHandler.js
- src/utils/flowUtilityTypes.js
- src/utils/getFlowTypeFromReactComponent.js
- src/utils/resolveGenericTypeAnnotation.js
> fix: Correctly unwrap utility types when resolving type spreads

- src/utils/__tests__/getPropType-test.js
- src/utils/getPropType.js
> fix: correctly read description of inner types in arrayOf/objectOf

- src/handlers/__tests__/componentMethodsJsDocHandler-test.js
- src/utils/__tests__/__snapshots__/parseJsDoc-test.js.snap
- src/utils/__tests__/parseJsDoc-test.js
- src/utils/parseJsDoc.js
BREAKING CHANGE: The type of method params and return is now aligned with
flow types.
fixes #285
> fix: Correctly and recursively parse jsdoc types

- package.json
- src/babelParser.js
- yarn.lock
https://babeljs.io/blog/2018/08/27/7.0.0
---
It's time to go away from beta :+1:
> chore(package): update Babel 7

- src/__tests__/__snapshots__/main-test.js.snap
- src/__tests__/fixtures/component_18.js
- src/resolver/findExportedComponentDefinition.js
- src/utils/getMemberExpressionValuePath.js
- src/utils/getMemberValuePath.js
- src/utils/isReactForwardRefCall.js
- recognizes `React.forwardRef` as a valid component in a hoc
- adds support for `propTypes` and `defaultProps` for `React.forwardRef` components
Started out as a simple fix to recognize `export default hoc(React.forwardRef(...))` until I realized that `forwardRef` is not supported in `propTypes` handler.
I can split those two up if you want to (moving propTypes to fixture 14 and simply using 18 as the hoc+forwardRef fixture). As far as I understood the codebase this needs to be ported to every resolver? I haven't used flow in over a year so everything flow related (as most of the other additions) is just copy and paste.
> Add forwardRef as a valid component definition

- src/utils/__tests__/getFlowType-test.js
- src/utils/getFlowType.js
- src/utils/resolveObjectKeysToArray.js
This adds support for ObjectTypeAnnotations as the typeParameter of $Keys.
This will now resolve to a union:
```
$Keys<{| a: string, b: string |}>
```
> Resolve flow $Keys to union when typeParameter is an ObjectTypeAnnotation

- src/utils/__tests__/__snapshots__/getPropType-test.js.snap
- src/utils/__tests__/getPropType-test.js
- src/utils/__tests__/resolveObjectValuesToArray-test.js
- src/utils/getPropType.js
- src/utils/resolveObjectValuesToArray.js
Adding compatibility for Object.values as suggested on #211 
Creates a new util to extract keys from Object.values() and ObjectExpressions when used inside of oneOf()
It also follows spreads and tries to resolve them. Currently it bails out if either a Property is computed and the computed key is not a Literal or if a spread cannot be resolved.
Getters and setters will be ignored and undefined values transform to a null Literal.
Added the tests and checked that passes the `test:ci` script.
> feat(resolve): resolve Object.values() in PropType.oneOf()

- .flowconfig
- README.md
- bin/react-docgen.js
- package.json
- src/__tests__/parse-test.js
- src/babelParser.js
- yarn.lock
Add `logicalAssignment` to the default plugins.
BREAKING CHANGE: Removed cli arguments `--legacy-decorators` and `--decorators-before-export`. Instead use a babel configuration file with the correct options for the transforms.
BREAKING CHANGE: Removed api options `legacyDecorators` and `decoratorsBeforeExport`. Instead use a babel configuration file or supply `parserOptions` and enable the plugins with the correct options.
Do you think this is okay and works with your usecases? I wanted to add this before doing 4.0.
So basically the options are now:
1. No config file and no parserOptions => defaultPlugins
2. No config file and parserOptions with plugins => parserOptions only
3. No config file and parserOptions without plugins => parserOptions + defaultPlugins
4. Config File and no …
> Support custom parser options in programmatic API

- src/types.js
- src/utils/__tests__/getPropType-test.js
- src/utils/getPropType.js
Introduced in facebook/prop-types#211, released in [`prop-types@15.7.0`](https://github.com/facebook/prop-types/blob/v15.7.0/CHANGELOG.md#1570).
> feat: support PropTypes.elementType

- README.md
- src/babelParser.js
I realized trying to get this to work with gatsby in a monorepo that react-docgen doesn't have enough info to resolve my local configs and babelrc
> feat: support all the config resolving related babel options

- src/__tests__/__snapshots__/main-test.js.snap
- src/__tests__/fixtures/component_19.js
- src/utils/getFlowType.js
The new fixtures shows an example that currently fails with the error
```
TypeError: Argument must be an Identifier or a Literal
at getNameOrValue (/home/fkling/git/react-docgen/dist/utils/getNameOrValue.js:40:13)
at getPropertyName (/home/fkling/git/react-docgen/dist/utils/getPropertyName.js:34:40)
at NodePath.path.get.each.param (/home/fkling/git/react-docgen/dist/utils/getFlowType.js:171:41)
at NodePath.each (/home/fkling/git/react-docgen/node_modules/ast-types/lib/path.js:89:26)
at Object.handleObjectTypeAnnotation [as ObjectTypeAnnotation] (/home/fkling/git/react-docgen/dist/utils/getFlowType.js:168:26)
at getFlowTypeWithResolvedTypes (/home/fkling/git/react-docgen/dist/utils/getFlowType.js:274:35)
at Object.handleGenericTypeAnnotation [as GenericTypeAnnotation] …
```
> [flow] Ignore spread properties in object type

- src/handlers/__tests__/__snapshots__/flowTypeHandler-test.js.snap
- src/handlers/__tests__/flowTypeHandler-test.js
- src/handlers/flowTypeHandler.js
- src/utils/__tests__/flowUtilityTypes-test.js
- src/utils/flowUtilityTypes.js
- src/utils/getFlowTypeFromReactComponent.js
- src/utils/resolveGenericTypeAnnotation.js
We only were resolving up to two levels, because we were doing it in two places :D
```js
type A = $Shape< $Shape< $Shape<B>>>
```
This also refactors the code so that we only do the unwrapping and resolving of types in one single place.
> Fix resolving of more than two Flow Utility types

- .eslintrc.js
- src/__tests__/__snapshots__/main-test.js.snap
- src/__tests__/fixtures/component_20.js
- src/handlers/__tests__/__snapshots__/componentMethodsHandler-test.js.snap
- src/handlers/__tests__/__snapshots__/defaultPropsHandler-test.js.snap
- src/handlers/__tests__/__snapshots__/flowTypeHandler-test.js.snap
- src/handlers/__tests__/__snapshots__/propTypeHandler-test.js.snap
- src/handlers/__tests__/componentMethodsHandler-test.js
- src/handlers/__tests__/defaultPropsHandler-test.js
- src/handlers/__tests__/flowTypeHandler-test.js
- src/handlers/__tests__/propTypeHandler-test.js
- src/handlers/componentMethodsHandler.js
- src/handlers/defaultPropsHandler.js
- src/handlers/flowTypeHandler.js
- src/handlers/propTypeHandler.js
- src/utils/__tests__/__snapshots__/getMethodDocumentation-test.js.snap
- src/utils/__tests__/__snapshots__/getPropType-test.js.snap
- src/utils/__tests__/getMethodDocumentation-test.js
- src/utils/__tests__/getPropType-test.js
- src/utils/__tests__/getPropertyName-test.js
- src/utils/getMethodDocumentation.js
- src/utils/getPropType.js
- src/utils/getPropertyName.js
- src/utils/isReactComponentMethod.js
- src/utils/setPropDescription.js
Fixes #317 
This ignores complex computed properties.
Non complex ones (identifiers, literals) are prefixed with `@computed#` and otherwise handled like normal.
> Handle computed properties correctly and do not fail generation

- src/utils/index.js
Forgot to export this in #311. Need this for a custom default props resolver and I'd rather use the public interface.
> fix: Add missing isReactForwardRefCall export

- src/handlers/__tests__/__snapshots__/defaultPropsHandler-test.js.snap
- src/handlers/__tests__/defaultPropsHandler-test.js
- src/handlers/defaultPropsHandler.js
In `React.forwardRef(({ foo = 'bar' }, ref) => <div ref={ref}>{foo}</div>)` the default props handler would not detect that `foo` had a default value.
I was curious if #343  would've fixed this as well but this is not the case.
> feat(defaultPropsHandler): Fully support forwardRef

- website/src/index.js
Resolves #372 by moving the isRequired PropType definition to a prop that does not have a defaultProp defined.
> Updated example with valid isRequired

- src/utils/__tests__/getTSType-test.js
- src/utils/getTSType.js
> Add support for TSMappedType

- src/utils/__tests__/resolveHOC-test.js
- src/utils/resolveHOC.js
Used when static properties need to be defined on intermediate values.
> fix: Hocs resolving intermediate values

- src/utils/__tests__/getTSType-test.js
- src/utils/getTSType.js
Fixes #367
I'm new to working with ASTs, and welcome any feedback. I also had some issues with type narrowing in Flow, resulting in the use of `$Shape<>`.
> Added handleTSIndexedAccessType.

- bin/react-docgen.js
The current implementation of `react-docgen` CLI doesn't support passing a single `*.ts(x)` file for parsing. As you can see from the source code, internal function `parse` is called with only one parameter (content of the required file), however, in order to specify that the file should be parsed according to the TypeScript spec, we need pass `options` to the `babelParser` that should contain a filename with `ts(x)` extension. If we don't pass `filePath` (see my patch), `options` object will become empty and `flow` parser will be used instead (which is incompatible with some TypeScript features).
This bug only affects react-codegen CLI tool
Pass `filePath` along with the file content
> Support ts(x) file parsing using CLI

- src/utils/__tests__/resolveHOC-test.js
- src/utils/resolveHOC.js
Unless we know for sure it is not a component (literal, array, object, spread)
I did some research too and it seem most HOC have the component as first like for example `relay` and `React.memo`.
In case though someone wrote a HOC that assumes the component is the last argument, this will break their documentation.
Fixes #342
> Assume HOC first param is Component not last

- src/utils/__tests__/isReactCloneElementCall-test.js
- src/utils/__tests__/isReactCreateClassCall-test.js
- src/utils/__tests__/isReactCreateElementCall-test.js
- src/utils/__tests__/isReactForwardRefCall-test.js
- src/utils/isReactBuiltinCall.js
- src/utils/isReactCloneElementCall.js
- src/utils/isReactCreateClassCall.js
- src/utils/isReactCreateElementCall.js
- src/utils/isReactForwardRefCall.js
Please review if this fix is useful.
Fixes #394 
Fixes #380
> Support destructuring and aliased imports in react builtin call detection

- src/resolver/__tests__/findAllComponentDefinitions-test.js
- src/resolver/findAllComponentDefinitions.js
Fixes #331
This is I think breaking as the following example will now detect a component:
```js
myFunctionCallWhichIsNotAHOC(something, node => (<div>{node}</div>), other);
```
And I don't see a way to workaround this as we cannot detect if a call is a HOC or not.
> Detect components wrapped in HOC with all resolver

- src/handlers/__tests__/componentMethodsHandler-test.js
- src/resolver/__tests__/findAllComponentDefinitions-test.js
- src/utils/__tests__/isReactComponentClass-test.js
- src/utils/isReactComponentClass.js
Previously a class just needed to have a `render` method.
Now it in addition requires to have a superclass as well.
Also adds support for `React.PureComponent` in `isReactComponentClass.js`
Subset of #354
> Be more strict about detecting react class components

- src/utils/__tests__/isStatelessComponent-test.js
- src/utils/isStatelessComponent.js
exported functions that are recursive will loop unless we check the resolution logic at some point
> fix: bail when function returns are recursive instead of stack overflowing

- src/utils/__tests__/resolveToValue-test.js
- src/utils/resolveToValue.js
> fix(typescript): Support type as expressions and type assertions

- src/utils/__tests__/getTSType-test.js
- src/utils/getTSType.js
fixes #410 
We were incorrectly forwarding the typeparams while resolving a new type (the resolved one) which might have new or different type params.
> Do not forward typeParameters when using resolved Path

- src/__tests__/__snapshots__/main-test.js.snap
- src/__tests__/fixtures/component_27.tsx
- src/utils/__tests__/__snapshots__/getMethodDocumentation-test.js.snap
- src/utils/__tests__/getMethodDocumentation-test.js
- src/utils/getMethodDocumentation.js
When generating documentation for methods in class components using TypeScript, I have some methods marked as `private` because they are internal and don't want to show them in the docs. But I don't have any information regarding whether a method is public or private in the currently extracted metadata. In this PR, I'm adding a modifier for private methods so I can know which methods to exclude.
> feat(typescript): add private modifier for private methods

- src/__tests__/__snapshots__/main-test.js.snap
- src/__tests__/fixtures/component_29.js
- src/__tests__/fixtures/component_30.js
- src/__tests__/fixtures/component_31.js
- src/__tests__/fixtures/component_32.js
- src/utils/getFlowType.js
Resolves https://github.com/reactjs/react-docgen/issues/427
Nested structs using generics currently cause a `maximum callstack exceeded` error. This PR resolves the issue by short-circuiting the recursion when the type resolves to a generic.
This approach has a shortcoming where the below example will resolve the prop `prop` as `T` instead of as `string`. But this is currently the same behavior seen when switching to typescript and should be fine since it's an an overall improvement to docgen erroring.
```jsx
import * as React from "react";
type Identity<T> = T;
type Props<T> = {
prop: Identity<T>;
}
export default function Test(props: Props<string>) {
return <div />;
}
```
I'm happy to iterate on this PR, let me know if you need me to change anything.
> Fix to Flow Maximum Callstack exceeded error on recursive generic structs

- src/utils/__tests__/getFlowType-test.js
- src/utils/getFlowType.js
The Flow `empty` type (`EmptyTypeAnnotation`) is currently represented by the catch-all string `"unknown"`. With this change it will be represented by `"empty"`.
> fix(flow): support empty type

- src/handlers/__tests__/__snapshots__/defaultPropsHandler-test.js.snap
- src/handlers/__tests__/defaultPropsHandler-test.js
- src/handlers/__tests__/flowTypeHandler-test.js
- src/handlers/defaultPropsHandler.js
- src/utils/getFlowTypeFromReactComponent.js
Enables handlers that support `forwardRef` (`defaultProps` and Flow type handling) to work when the argument to `forwardRef` is a reference to a function defined outside of the `forwardRef` call:
```jsx
import React from 'react';
const ComponentImpl = ({ foo = 'bar' }, ref) => <div ref={ref}>{foo}</div>;
React.forwardRef(ComponentImpl);
```
This is achieved by reusing `resolveToValue`.
Note that this does **not** fix the rebinding case, which I intend to tackle separately:
```jsx
import React from 'react';
let ComponentImpl = ({ foo = 'bar' }, ref) => <div ref={ref}>{foo}</div>;
ComponentImpl = React.forwardRef(ComponentImpl); // resolveToValue resolves here :/
```
> fix: support forwardRef with out of line argument

- src/utils/resolveToValue.js
- src/utils/traverse.js
Traversing with `visit` using a node as the root creates a new `NodePath`, which detaches the resulting paths from the root `File` node. I've seen this lead to `getFlowType` crashing later when it tries to grab the source code from the no-longer-reachable `File` node[1]. Traversing from a `NodePath` keeps everything correctly linked and has no downsides AFAICT, so here I changed `traverseShallow` (which wraps `visit`) to only accept paths.
[1] I don't have the exact repro case to hand, unfortunately, but this was in the course of working on https://github.com/facebook/react-native-website/pull/1628.
> fix(traverse): only visit paths, not nodes

- src/handlers/__tests__/flowTypeHandler-test.js
- src/utils/__tests__/resolveToValue-test.js
- src/utils/resolveToValue.js
When calling `resolveToValue`, currently it may resolve to an expression containing the very reference we were trying to resolve, even though the correct resolution in terms of program flow is an earlier assignment. In particular, this arises in some handlers when we reassign a variable holding a component, e.g when wrapping it with a HOC:
```jsx
import React from 'react';
let Component = (props, ref) => {};
//              ^
//              expected resolution
Component = React.forwardRef(     Component     );
//          ^                     ^
//          actual resolution     reference
```
Here, we minimally tweak `resolveToValue` to (1) take an Identifier path instead of a name; and (2) not resolve to an assignment expression's RHS if the assignment contains the reference we're …
> fix: avoid circular reference when resolving name from within assignment

- src/handlers/__tests__/displayNameHandler-test.js
- src/handlers/displayNameHandler.js
Makes `displayNameHandler` succeed when invoked on the `CallExpression` node representing a ` forwardRef` call, rather than on the function expression that is its argument. (The latter scenario already works and is what the existing tests cover.)
> fix: infer displayName given forwardRef() node

- src/handlers/__tests__/componentDocblockHandler-test.js
- src/handlers/componentDocblockHandler.js
In the same vein as #430. With this change, we read the description docblock for a `forwardRef`'d function component either from the `forwardRef` call itself, or failing that, from its resolved argument.
> fix: handle docblock on out-of-line forwardRef

- src/handlers/__tests__/__snapshots__/componentMethodsHandler-test.js.snap
- src/handlers/__tests__/componentMethodsHandler-test.js
- src/handlers/componentMethodsHandler.js
- src/utils/getMethodDocumentation.js
Extends `componentMethodsHandler` to recognise static methods added to function components via assignment. Internally to the handler, methods may now be represented either by `AssignmentExpression` nodes or by object/class method nodes.
> feat(methods): support static methods on function components

- README.md
I tried to understand how to use the resolvers and was not clear for me how to do that until googling and landing in this issue https://github.com/reactjs/react-docgen/issues/244 which asked to improve the documentation, which ended with this PR https://github.com/reactjs/react-docgen/pull/328 which improved as well the documentation, but wasn't that clear to me, because I read that part of the documentation, I think adding the `reactDocs.parse` is crystal clear how to use it.
> Improving resolver documentation 2.0

- src/handlers/__tests__/componentMethodsHandler-test.js
- src/handlers/componentMethodsHandler.js
Currently, react-docgen fails to parse a component that uses private properties such as
```jsx
class MyComponent extends React.Component {
#privateCallback = () => {
console.log('Do something');
}
render() {
return <button onClick={this.#privateCallback}>Click me</button>
}
}
```
This fix allows react-docgen to parse this code.
- Surprisingly `t.ClassProperty.check` returns true even if the property is a `ClassPrivateProperty`. This explains the nature of the change, and why there seems to be a seemingly contradicting line: `t.ClassProperty.check(path.node) && !t.ClassPrivateProperty.check(path.node)`
> Ensure componentMethodsHandler ignores private properties

- website/webpack.config.js
I believe this fix the playground, with a bug introduced in https://github.com/reactjs/react-docgen/commit/a3789033ee5507f8f0214847e638b4b47cfc0d4f.
http://reactcommunity.org/react-docgen/
> Fix "Buffer is not defined" on website

- src/utils/__tests__/__snapshots__/resolveObjectKeysToArray-test.ts.snap
- src/utils/__tests__/__snapshots__/resolveObjectValuesToArray-test.ts.snap
- src/utils/__tests__/resolveObjectKeysToArray-test.ts
- src/utils/__tests__/resolveObjectValuesToArray-test.ts
- src/utils/getPropType.ts
- src/utils/resolveObjectKeysToArray.ts
- src/utils/resolveObjectValuesToArray.ts
BREAKING CHANGE: The helpers `resolveObjectValuesToArray` and `resolveObjectKeysToArray` return now `string[]` instead of a `NodePath`
> fix: Remove usage of ast-type builders

- src/__tests__/__snapshots__/main-test.ts.snap
- src/__tests__/fixtures/component_43.tsx
- src/utils/__tests__/expressionTo-test.ts
- src/utils/expressionTo.ts
Using a combination of forwardRefs and generics leads to wanting to use type assertions to retain the generic nature of the wrapped class.  This plays rather poorly with propTypes.  After a lot of mucking around I decided to simply assert the desired type when setting propTypes and defaults.
This leads to code like this:
```tsx
(MenuItem as ComponentObjectOf<typeof MenuItem>).propTypes - {...}
```
This change extends expressionTo.toArray to deal with the typescript expression.
> Add support for TSAsExpressions when trying to stringify expressions

- packages/react-docgen/src/Documentation.ts
- packages/react-docgen/src/utils/getTSType.ts
- packages/react-docgen/tests/integration/__fixtures__/component_22.tsx
- packages/react-docgen/tests/integration/__snapshots__/integration-test.ts.snap
Fixes: #496
For something like:
```tsx
type Props = {
...
center: {
/** x coordinate */
x : number,
/** y coordinate */
y: number;
}
}
```
Fill out `description` fields with appropriate jdoc for `x` and `y`
> fix(ts): parse jsdoc comment for ts structs

- packages/react-docgen/src/handlers/__tests__/__snapshots__/componentMethodsHandler-test.ts.snap
- packages/react-docgen/src/handlers/__tests__/componentMethodsHandler-test.ts
- packages/react-docgen/src/handlers/componentMethodsHandler.ts
- packages/react-docgen/src/utils/__tests__/findFunctionReturn-test.ts
- packages/react-docgen/src/utils/__tests__/isStatelessComponent-test.ts
- packages/react-docgen/src/utils/findFunctionReturn.ts
- packages/react-docgen/src/utils/isStatelessComponent.ts
Fixes #454 
Fixes #591 
This is based on the other two PRs, but I refactored other parts to be able to reuse them in the detection for hooks.
> feat: Add support for useImperativeHandle

- .changeset/five-trainers-report.md
- packages/react-docgen/src/resolver/FindExportedDefinitionsResolver.ts
- packages/react-docgen/src/utils/findComponentDefinition.ts
Refactored `resolveComponentDefinition` utility.
- Renamed to `findComponentDefinition`
- Removed named export `isComponentDefinition`
- The utility now does a lot more than previously, check out the commit to see
the changes in detail.
> Refactor resolveComponentDefinition into findComponentDefinition

- .changeset/seven-camels-flash.md
- packages/react-docgen/src/utils/__tests__/__snapshots__/getPropType-test.ts.snap
- packages/react-docgen/src/utils/__tests__/getPropType-test.ts
- packages/react-docgen/src/utils/getPropType.ts
- tsconfig.base.json
> Handle cycle in PropTypes shapeish validators

- .changeset/nasty-onions-fly.md
- packages/react-docgen/src/utils/__tests__/__snapshots__/getPropType-test.ts.snap
- packages/react-docgen/src/utils/__tests__/getPropType-test.ts
- packages/react-docgen/src/utils/__tests__/resolveObjectKeysToArray-test.ts
- packages/react-docgen/src/utils/__tests__/resolveObjectValuesToArray-test.ts
- packages/react-docgen/src/utils/getPropType.ts
> Fix prop-types oneOf not handling unresolved imports

- .changeset/witty-ligers-press.md
- packages/react-docgen/src/utils/__tests__/__snapshots__/getPropType-test.ts.snap
- packages/react-docgen/src/utils/__tests__/getPropType-test.ts
- packages/react-docgen/src/utils/resolveObjectValuesToArray.ts
> Correctly resolve values in `Object.values`

- .changeset/fuzzy-rice-dance.md
- packages/react-docgen/src/FileState.ts
- packages/react-docgen/src/utils/findFunctionReturn.ts
- packages/react-docgen/src/utils/getFlowType.ts
- packages/react-docgen/src/utils/getMethodDocumentation.ts
- packages/react-docgen/src/utils/getTypeAnnotation.ts
For https://github.com/storybookjs/storybook/pull/22324
> Fix typescript types without strict null checks

- .changeset/eleven-camels-sleep.md
- packages/react-docgen/src/handlers/componentMethodsJsDocHandler.ts
- packages/react-docgen/src/utils/__tests__/getMethodDocumentation-test.ts
- packages/react-docgen/src/utils/__tests__/normalizeClassDefinition-test.ts
- packages/react-docgen/src/utils/normalizeClassDefinition.ts
> copy comments when converting to class-properties

- .changeset/short-squids-knock.md
- packages/react-docgen/src/utils/__tests__/__snapshots__/getFlowType-test.ts.snap
- packages/react-docgen/src/utils/__tests__/getFlowType-test.ts
- packages/react-docgen/src/utils/getFlowType.ts
Ref #683
Fixes the initial reported issue in the ticket above.
> read dockblock from nested flow object types

- .changeset/hungry-sheep-laugh.md
- packages/react-docgen/src/utils/__tests__/__snapshots__/getTSType-test.ts.snap
- packages/react-docgen/src/utils/__tests__/getTSType-test.ts
- packages/react-docgen/src/utils/getTSType.ts
- pnpm-workspace.yaml
> correctly support ObjectPattern and ArrayPattern in function signatures

- .changeset/tender-rings-live.md
- packages/react-docgen/src/utils/__tests__/__snapshots__/getFlowType-test.ts.snap
- packages/react-docgen/src/utils/__tests__/getFlowType-test.ts
- packages/react-docgen/src/utils/getFlowType.ts
- packages/react-docgen/src/utils/getTSType.ts
> Fix support for index types in flow

- packages/website/src/pages/docs/reference/_meta.json
- packages/website/src/pages/docs/reference/api.mdx
- packages/website/src/pages/docs/reference/config.mdx
- packages/website/src/pages/docs/reference/documentation/flow.mdx
- packages/website/src/pages/docs/reference/documentation/typescript.mdx
I got confused by two links being completely dead in the docs.
At least I'm adding blank pages so that the links are clickable.
Fixes #825
> Add missing pages, add ContentMissing component to blank pages

- .changeset/itchy-planets-heal.md
- packages/react-docgen/src/utils/__tests__/resolveExportDeclaration-test.ts
- packages/react-docgen/src/utils/resolveExportDeclaration.ts
- packages/react-docgen/tests/integration/__fixtures__/namespace-export.tsx
- packages/react-docgen/tests/integration/__snapshots__/integration-test.ts.snap
> Fix handling of exports with namespace specifiers
